import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-lvh bg-gray-900 text-white flex flex-col justify-between space-y-10">
        <header>
          <Navbar />
        </header>
        <main className="flex justify-center">
          <div className="md:min-h-[70lvh] w-3/4 md:8/12 flex flex-row justify-center ">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
